name: Build WindUI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.1"

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0

      - name: Install Rojo, Lune and DarkLua
        run: aftman install

      - name: Run build
        run: npm run build

      - name: Create/Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: latest
          files: dist/main.lua
          make_latest: true
